language: generic
sudo: required
services:
  - docker

script:
  - docker build -t mozilla/lua_sandbox_extensions .
  - |
    docker run --rm mozilla/lua_sandbox_extensions \
    bash -c 'cd /root/lua_sandbox_extensions/release && ctest -V -C integration'
  - mkdir dist
  - |
    docker run -v `pwd`/dist:/dist --rm mozilla/lua_sandbox_extensions \
    bash -c 'cp /root/lua_sandbox_extensions/release/*.rpm /dist'
  - sha256sum dist/*

deploy:
  - provider: script
    script: bash artifact_push.sh
    skip_cleanup: true
    on:
      all_branches: true
      condition: $TRAVIS_BRANCH =~ ^dev|master$
  - provider: script
    script: bash docker_push.sh $TRAVIS_BRANCH
    on:
      all_branches: true
      condition: $TRAVIS_BRANCH =~ ^dev|master|test$
